/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        // Obsidian Kinetic palette
        surface: "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#3a3939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "surface-variant": "#353534",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#e7bdb2",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        outline: "#ad887e",
        "outline-variant": "#5d4038",
        "surface-tint": "#ffb5a0",
        primary: "#ffb5a0",
        "on-primary": "#601400",
        "primary-container": "#ff5625",
        "on-primary-container": "#541100",
        "inverse-primary": "#b12d00",
        secondary: "#c6c6c7",
        "on-secondary": "#2f3131",
        "secondary-container": "#454747",
        "on-secondary-container": "#b4b5b5",
        tertiary: "#ffb59a",
        "on-tertiary": "#5a1b00",
        "tertiary-container": "#f46220",
        "on-tertiary-container": "#4f1700",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#ffdbd1",
        "primary-fixed-dim": "#ffb5a0",
        "on-primary-fixed": "#3b0900",
        "on-primary-fixed-variant": "#872000",
        "secondary-fixed": "#e2e2e2",
        "secondary-fixed-dim": "#c6c6c7",
        "on-secondary-fixed": "#1a1c1c",
        "on-secondary-fixed-variant": "#454747",
        "tertiary-fixed": "#ffdbce",
        "tertiary-fixed-dim": "#ffb59a",
        "on-tertiary-fixed": "#370e00",
        "on-tertiary-fixed-variant": "#802a00",
        background: "#131313",
        "on-background": "#e5e2e1",
        // functional signal states
        "text-primary": "#ffffff",
        "text-muted": "#737373",
        "critical-risk": "#ff3333",
        "guarded": "#2ee59d",
        "elevated-threat": "#ff4500",
      },
      fontFamily: {
        anton: ["Anton", "system-ui", "sans-serif"],
        body: ["Space Grotesk", "system-ui", "sans-serif"],
        mono: ["'JetBrains Mono'", "ui-monospace", "monospace"],
      },
      fontSize: {
        "display-xl": ["80px", { lineHeight: "84px", letterSpacing: "0.02em", fontWeight: "400" }],
        "display-xl-mobile": ["48px", { lineHeight: "52px", letterSpacing: "0.02em", fontWeight: "400" }],
        "headline-lg": ["44px", { lineHeight: "48px", letterSpacing: "0.03em", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "36px", letterSpacing: "0.03em", fontWeight: "400" }],
        "headline-md": ["28px", { lineHeight: "32px", letterSpacing: "0.04em", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "24px", letterSpacing: "0.04em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "18px", letterSpacing: "0.08em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "500" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.14em", fontWeight: "600" }],
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "space-2xl": "4rem",
        "margin": "2.5rem",
        "margin-mobile": "1rem",
        "gutter": "1.5rem",
        "gutter-mobile": "0.75rem",
      },
      boxShadow: {
        "glow-primary": "0 0 12px rgba(255,86,37,0.35)",
        "glow-danger": "0 0 12px rgba(255,51,51,0.4)",
      },
      keyframes: {
        "fade-up": {
          "0%": { opacity: 0, transform: "translateY(12px)" },
          "100%": { opacity: 1, transform: "translateY(0)" },
        },
        shimmer: {
          "100%": { transform: "translateX(100%)" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: 1, transform: "scale(1)" },
          "50%": { opacity: "0.75", transform: "scale(1.02)" },
        },
        "spin-slow": {
          "100%": { transform: "rotate(360deg)" },
        },
      },
      animation: {
        "fade-up": "fade-up 0.4s cubic-bezier(0.16,1,0.3,1) both",
        shimmer: "shimmer 1.5s infinite",
        "pulse-soft": "pulse-soft 2.4s ease-in-out infinite",
        "spin-slow": "spin-slow 2s linear infinite",
      },
    },
  },
  plugins: [],
};