import { FileText } from "lucide-react";
import Breadcrumbs from "../components/Breadcrumbs";
import { SITE_NAME } from "../lib/site";
import { useDocumentMeta } from "../lib/useDocumentMeta";

export default function Terms() {
  useDocumentMeta({
    title: `Terms & Conditions - ${SITE_NAME}`,
    description: "Terms and conditions for using the ScamShield AI scam detection and intelligence platform.",
    path: "/terms",
  });

  return (
    <div className="animate-fade-up max-w-4xl mx-auto pb-12">
      <Breadcrumbs items={[{ label: "Terms & Conditions" }]} />
      <div className="card space-y-6">
        <div className="flex items-center gap-3 border-b border-white/10 pb-4">
          <div className="grid place-items-center h-10 w-10 rounded-xl bg-accent/15 border border-accent/30">
            <FileText className="h-5 w-5 text-accent" />
          </div>
          <div>
            <h1 className="text-xl font-bold text-white">Terms & Conditions</h1>
            <p className="text-xs text-slate-400">Last updated: September 21, 2026</p>
          </div>
        </div>

        <div className="space-y-4 text-sm text-slate-300 leading-relaxed">
          <h2 className="text-base font-semibold text-white mt-6">1. Acceptance of Terms</h2>
          <p>
            By accessing or using ScamShield AI, you agree to be bound by these Terms and Conditions.
            If you do not agree to these terms, please do not use the service.
          </p>

          <h2 className="text-base font-semibold text-white mt-6">2. Description of Service</h2>
          <p>
            ScamShield AI provides automated scam analysis, threat risk scoring, and cross-channel campaign
            correlation for educational, defensive, and threat assessment purposes.
          </p>

          <h2 className="text-base font-semibold text-white mt-6">3. Disclaimer of Warranties</h2>
          <p>
            The risk assessments and threat reports provided by ScamShield AI are generated by automated
            rule systems, heuristic models, and third-party threat feeds. While we strive for accuracy,
            no automated system can guarantee 100% detection of all threats or complete absence of false positives.
            The service is provided on an "AS IS" and "AS AVAILABLE" basis.
          </p>

          <h2 className="text-base font-semibold text-white mt-6">4. Acceptable Use</h2>
          <p>
            You agree not to use ScamShield AI to conduct denial-of-service attacks, reverse engineer detection
            mechanisms for malicious evasion, or submit illegal materials.
          </p>

          <h2 className="text-base font-semibold text-white mt-6">5. Changes to Terms</h2>
          <p>
            We reserve the right to update these terms at any time. Continued use of the service following
            updates constitutes acceptance of modified terms.
          </p>
        </div>
      </div>
    </div>
  );
}
